const translations = {
  en: {
    brand: "TunisiaDrive Academy",
    brand_sub: "Driving school | مدرسة تعليم السياقة",
    nav_home: "Home",
    nav_about: "About",
    nav_services: "Services",
    nav_booking: "Booking",
    nav_prices: "Prices",
    nav_learning: "Resources",
    nav_contact: "Contact",
    nav_cta: "Book now",
    hero_badge: "Based in Tunisia • Safe & modern driving",
    hero_title: "Drive with confidence, drive with safety.",
    hero_sub: "Modern lessons, certified instructors, and smart planning to get you test-ready faster.",
    cta_book: "Book now",
    cta_contact: "Contact us",
    cta_prices: "View prices",
    stat_success: "Exam success rate",
    stat_students: "Students trained",
    stat_languages: "Languages: AR / FR / EN",
    hero_car1_title: "Practice in comfort",
    hero_car1_sub: "Dual control, fully insured",
    hero_car2_title: "Master every road",
    hero_car2_sub: "City • Highway • Night",
    badge_cert: "Certified & licensed instructors",
    badge_schedule: "Flexible scheduling",
    badge_payment: "Secure online payments",
    about_label: "Who we are",
    about_title: "Driving excellence across Tunisia.",
    about_text:
      "TunisiaDrive Academy blends local expertise with modern training. From your first start to your exam day, we guide you with structured lessons, real feedback, and professional safety standards.",
    about_history_title: "Our story",
    about_history_text: "Founded in 2010 in Tunis, now serving students nationwide with urban, coastal, and highway programs.",
    about_mission_title: "Mission & values",
    about_mission_text: "Safety, professionalism, and measurable success are at the heart of every lesson.",
    chip_safety: "Safety first",
    chip_prof: "Professional coaching",
    chip_success: "High success rate",
    about_team_title: "Certified instructors",
    about_instr1: "10 yrs experience • Manual",
    about_instr2: "Highway & night driving",
    about_instr3: "Theory & exam coaching",
    about_certs: "Licensed by the Tunisian Ministry of Transport • Defensive driving certified • First-aid trained",
    services_label: "Programs",
    services_title: "Services built for every driver.",
    svc_manual: "Manual & automatic lessons",
    svc_intensive: "Intensive classes",
    svc_intensive_desc: "Accelerated paths with daily practice for faster readiness.",
    svc_night: "Night driving training",
    svc_night_desc: "Master visibility, headlights etiquette, and fatigue control.",
    svc_highway: "Highway practice",
    svc_highway_desc: "On-ramp, overtaking, and speed management with experts.",
    svc_parking: "Parking practice",
    svc_parking_desc: "Parallel, bay, and hill-start drills until you’re confident.",
    svc_exam: "Exam preparation",
    svc_exam_desc: "Theory + practical simulations with official marking criteria.",
    svc_manual_desc: "Adapted to your preference with dual-control vehicles.",
    booking_label: "Booking & scheduling",
    booking_title: "Book online, pick an instructor, and pay securely.",
    booking_text: "Reserve lessons, choose manual or automatic, and manage your schedule from one place.",
    form_lesson: "Lesson type",
    form_instructor: "Reserve your instructor",
    form_date: "Choose date",
    form_time: "Choose time",
    form_package: "Package",
    form_payment: "Secure payment",
    form_submit: "Confirm booking",
    opt_manual1: "Manual - 1h",
    opt_manual2: "Manual - 2h",
    opt_auto1: "Automatic - 1h",
    opt_auto2: "Automatic - 2h",
    opt_intensive: "Intensive (10h week)",
    opt_exam_pack: "Exam package",
    opt_single: "Single session",
    opt_5h: "5h pack",
    opt_10h: "10h pack",
    opt_20h: "20h mastery",
    opt_card: "Credit / Debit",
    opt_transfer: "Instant transfer",
    opt_cash: "Cash at office",
    student_area_title: "Student area",
    student_area_text: "Log in to view your schedule, progress, and exam documents.",
    login_btn: "Student login",
    progress_label: "Progress tracking",
    prog_item1: "✔ Theory modules: 80%",
    prog_item2: "✔ City driving: 70%",
    prog_item3: "• Parking drills: 50%",
    notif_label: "Upcoming lessons",
    notif_item1: "Tue 10:00 — Manual with Amine",
    notif_item2: "Thu 18:00 — Night driving with Leila",
    notif_item3: "Sat 09:00 — Exam simulation with Sami",
    docs_label: "Exam documents",
    doc_item1: "Theory mock results (PDF)",
    doc_item2: "Practical checklist",
    doc_item3: "Insurance & license copies",
    prices_label: "Pricing",
    prices_title: "Transparent prices and flexible packs.",
    price_hourly: "Price per hour",
    price_hour_desc: "Manual or automatic • Car included",
    price_packages: "Packages",
    price_package_text: "Ideal for steady progress with savings.",
    price_exam: "Exam packages",
    price_exam1: "Mock exam + feedback",
    price_exam2: "Exam day car + coach",
    price_exam3: "Paperwork & scheduling help",
    price_discounts: "Discounts",
    disc_student: "Student discount -10%",
    disc_group: "Group discount -15%",
    disc_friend: "Bring-a-friend bonus ride",
    learning_label: "Learning resources",
    learning_title: "Theory, practice, and tips all in one place.",
    learn_theory: "Theory test materials",
    learn_signs: "Traffic signs explanations",
    learn_rules: "Road rules in Tunisia",
    learn_pdfs: "Downloadable PDFs",
    learn_tips: "Driving tips",
    tip_parallel: "How to parallel park",
    tip_roundabout: "Managing roundabouts",
    tip_hill: "Hill start basics",
    tip_mistakes: "Beginner mistakes to avoid",
    learn_quiz: "Practice quizzes",
    learn_quiz_desc: "MCQs with instant feedback and timed mock exams.",
    learn_quiz_btn: "Start a mock exam",
    quiz1: "Quiz 1 — Road rules",
    quiz2: "Quiz 2 — Signs & markings",
    quiz3: "Mock exam — 40 questions",
    learn_videos: "Video tutorials",
    learn_advice: "Instructor advice and visual explanations for maneuvers.",
    student_label: "Student area",
    student_title: "Track progress, notifications, and results.",
    student_progress: "Progress tracker",
    student_progress_desc: "See your completion by category and upcoming milestones.",
    stud_prog1: "Roundabouts: 80%",
    stud_prog2: "Parking: 70%",
    stud_prog3: "Highway: 65%",
    student_notifications: "Notifications",
    student_notifications_desc: "Reminders for lessons and exam dates.",
    stud_notif1: "Lesson tomorrow at 09:00",
    stud_notif2: "Mock theory on Friday",
    student_results: "Practice results",
    student_results_desc: "Theory test performance and downloadable reports.",
    stud_res1: "Last mock: 36 / 40 (90%)",
    stud_res2: "Average reaction time: 1.1s",
    stud_res3: "Download results (PDF)",
    test_label: "Testimonials",
    test_title: "Success stories from our students.",
    test1_text: "“Passed on my first try! Night driving sessions were a game changer.”",
    test1_meta: "Exam passed • Tunis",
    test2_text: "“Loved the clear feedback after each mock exam. Great instructors.”",
    test2_meta: "Automatic license • Sousse",
    test3_text: "“Highway and parking practice were spot on. Scheduling was easy.”",
    test3_meta: "Manual license • Sfax",
    blog_label: "Blog ideas",
    blog_title: "Guides for confident drivers.",
    blog1_title: "How to pass your driving test on the first try",
    blog1_desc: "Preparation checklist, examiner expectations, and mindset tips.",
    blog2_title: "Tips for nervous drivers",
    blog2_desc: "Breathing, scenario practice, and building confidence step by step.",
    blog3_title: "Difference between manual & automatic driving",
    blog3_desc: "Pros, cons, and how to decide based on your goals in Tunisia.",
    blog4_title: "How to choose a driving instructor",
    blog4_desc: "Credentials to verify and questions to ask before you book.",
    faq_label: "FAQs & policies",
    faq_title: "Everything you need to know.",
    faq_q1: "What cars do you use?",
    faq_a1: "Modern dual-control vehicles, manual and automatic, fully insured.",
    faq_q2: "Do you offer multilingual lessons?",
    faq_a2: "Yes: Arabic, French, and English — select your preference when booking.",
    faq_q3: "Refund policy",
    faq_a3: "48h notice for cancellations. Unused packages are refundable minus admin fees.",
    faq_q4: "Terms & conditions",
    faq_a4: "Safe behavior required; valid ID needed; payments secured via SSL.",
    faq_q5: "Live chat support",
    faq_a5: "Chat with us for scheduling, payments, or quick driving tips.",
    contact_label: "Contact & location",
    contact_title: "Reach us, visit us, or chat instantly.",
    contact_name: "Your name",
    contact_message: "Message",
    contact_send: "Send message",
    contact_hours: "Working hours",
    contact_hours_text: "Mon–Fri: 08:00–19:00 • Sat: 09:00–14:00",
    whatsapp_btn: "WhatsApp us",
    contact_location: "Tunis center",
    contact_phone: "+216 00 000 000",
    contact_email: "info@tunisiadrive.tn",
    footer_text: "Ready to drive with confidence? Book your first lesson today.",
    footer_terms: "Terms & conditions",
    footer_refund: "Refund policy",
    footer_support: "Live chat & support",
    chat_toggle: "Live chat",
    chat_title: "Live Support",
    chat_sub: "Typically replies in 2 minutes",
    chat_welcome: "Hi! Need help booking or understanding the exam?",
    chat_send: "Send",
    chat_reply: "Thanks! A coach will reply within minutes.",
    alert_booking: "Your lesson is reserved! A confirmation email will be sent shortly.",
    alert_contact: "Message sent! We will call or email you within 1 business hour.",
    alert_login: "Logged in (demo). Check your upcoming lessons below.",
    ph_name: "Full name",
    ph_contact_email: "you@email.com",
    ph_message: "How can we help?",
    ph_email: "Email",
    ph_password: "Password",
    ph_chat: "Type your question...",
  },
  fr: {
    brand: "TunisiaDrive Academy",
    brand_sub: "École de conduite | مدرسة تعليم السياقة",
    nav_home: "Accueil",
    nav_about: "À propos",
    nav_services: "Services",
    nav_booking: "Réservation",
    nav_prices: "Tarifs",
    nav_learning: "Ressources",
    nav_contact: "Contact",
    nav_cta: "Réserver",
    hero_badge: "Basée en Tunisie • Conduite sûre et moderne",
    hero_title: "Conduisez avec confiance et sécurité.",
    hero_sub: "Cours modernes, moniteurs certifiés et planning intelligent pour réussir plus vite.",
    cta_book: "Réserver",
    cta_contact: "Nous contacter",
    cta_prices: "Voir les tarifs",
    stat_success: "Taux de réussite",
    stat_students: "Élèves formés",
    stat_languages: "Langues : AR / FR / EN",
    hero_car1_title: "Pratique en confort",
    hero_car1_sub: "Double commande, assuré",
    hero_car2_title: "Maîtrisez chaque route",
    hero_car2_sub: "Ville • Autoroute • Nuit",
    badge_cert: "Moniteurs certifiés et licenciés",
    badge_schedule: "Horaires flexibles",
    badge_payment: "Paiements sécurisés",
    about_label: "Qui sommes-nous",
    about_title: "L'excellence de la conduite en Tunisie.",
    about_text:
      "TunisiaDrive Academy allie expertise locale et formation moderne. Du premier démarrage au jour d'examen, nous vous guidons avec des cours structurés et un vrai retour.",
    about_history_title: "Notre histoire",
    about_history_text: "Fondée en 2010 à Tunis, nous servons désormais des élèves partout en Tunisie.",
    about_mission_title: "Mission & valeurs",
    about_mission_text: "Sécurité, professionnalisme et réussite mesurable dans chaque leçon.",
    chip_safety: "Sécurité d'abord",
    chip_prof: "Coaching pro",
    chip_success: "Taux de réussite élevé",
    about_team_title: "Moniteurs certifiés",
    about_instr1: "10 ans d'expérience • Boîte manuelle",
    about_instr2: "Autoroute & conduite de nuit",
    about_instr3: "Théorie & coaching examen",
    about_certs: "Agrée Ministère des Transports • Conduite défensive • Premiers secours",
    services_label: "Programmes",
    services_title: "Des services pour chaque conducteur.",
    svc_manual: "Cours boîte manuelle et auto",
    svc_intensive: "Stages intensifs",
    svc_intensive_desc: "Parcours accélérés avec pratique quotidienne pour être prêt plus vite.",
    svc_night: "Formation conduite de nuit",
    svc_night_desc: "Maîtrise de la visibilité, des feux et de la fatigue.",
    svc_highway: "Pratique autoroute",
    svc_highway_desc: "Entrées, dépassements et gestion de la vitesse avec un pro.",
    svc_parking: "Entraînement parking",
    svc_parking_desc: "Créneau, bataille, en côte jusqu'à pleine confiance.",
    svc_exam: "Préparation examen",
    svc_exam_desc: "Simulations théoriques et pratiques avec critères officiels.",
    svc_manual_desc: "Adapté à votre choix avec véhicules à double commande.",
    booking_label: "Réservation & planning",
    booking_title: "Réservez en ligne, choisissez un moniteur, payez en sécurité.",
    booking_text: "Réservez vos cours, manuel ou auto, et gérez votre planning au même endroit.",
    form_lesson: "Type de cours",
    form_instructor: "Choisir le moniteur",
    form_date: "Choisir la date",
    form_time: "Choisir l'heure",
    form_package: "Forfait",
    form_payment: "Paiement sécurisé",
    form_submit: "Confirmer la réservation",
    opt_manual1: "Manuelle - 1h",
    opt_manual2: "Manuelle - 2h",
    opt_auto1: "Automatique - 1h",
    opt_auto2: "Automatique - 2h",
    opt_intensive: "Intensif (10h semaine)",
    opt_exam_pack: "Forfait examen",
    opt_single: "Séance unique",
    opt_5h: "Pack 5h",
    opt_10h: "Pack 10h",
    opt_20h: "Pack 20h",
    opt_card: "Carte bancaire",
    opt_transfer: "Virement instantané",
    opt_cash: "Espèces au bureau",
    student_area_title: "Espace élève",
    student_area_text: "Connectez-vous pour voir planning, progrès et documents d'examen.",
    login_btn: "Connexion élève",
    progress_label: "Suivi de progression",
    prog_item1: "✔ Modules théorie : 80%",
    prog_item2: "✔ Conduite urbaine : 70%",
    prog_item3: "• Exos parking : 50%",
    notif_label: "Prochains cours",
    notif_item1: "Mar 10:00 — Manuelle avec Amine",
    notif_item2: "Jeu 18:00 — Nuit avec Leila",
    notif_item3: "Sam 09:00 — Simulation examen avec Sami",
    docs_label: "Documents d'examen",
    doc_item1: "Résultats mock théorie (PDF)",
    doc_item2: "Checklist pratique",
    doc_item3: "Assurance & copies permis",
    prices_label: "Tarifs",
    prices_title: "Des prix transparents et des packs flexibles.",
    price_hourly: "Tarif horaire",
    price_hour_desc: "Manuelle ou auto • Véhicule inclus",
    price_packages: "Forfaits",
    price_package_text: "Idéal pour progresser et économiser.",
    price_exam: "Packs examen",
    price_exam1: "Mock examen + feedback",
    price_exam2: "Jour J : voiture + coach",
    price_exam3: "Aide paperasse & planning",
    price_discounts: "Réductions",
    disc_student: "Réduc étudiant -10%",
    disc_group: "Réduc groupe -15%",
    disc_friend: "Bonus si vous venez avec un ami",
    learning_label: "Ressources",
    learning_title: "Théorie, pratique et conseils au même endroit.",
    learn_theory: "Supports théoriques",
    learn_signs: "Explications des panneaux",
    learn_rules: "Code de la route en Tunisie",
    learn_pdfs: "PDF à télécharger",
    learn_tips: "Conseils de conduite",
    tip_parallel: "Réussir un créneau",
    tip_roundabout: "Gérer un rond-point",
    tip_hill: "Démarrage en côte",
    tip_mistakes: "Erreurs débutant à éviter",
    learn_quiz: "Quiz d'entraînement",
    learn_quiz_desc: "QCM avec feedback immédiat et mocks chronométrés.",
    learn_quiz_btn: "Lancer un mock",
    quiz1: "Quiz 1 — Code de la route",
    quiz2: "Quiz 2 — Panneaux & marquages",
    quiz3: "Mock examen — 40 questions",
    learn_videos: "Tutoriels vidéo",
    learn_advice: "Conseils moniteur et explications visuelles.",
    student_label: "Espace élève",
    student_title: "Suivez progrès, notifications et résultats.",
    student_progress: "Suivi de progression",
    student_progress_desc: "Visualisez vos complétions par catégorie.",
    stud_prog1: "Rond-points : 80%",
    stud_prog2: "Parking : 70%",
    stud_prog3: "Autoroute : 65%",
    student_notifications: "Notifications",
    student_notifications_desc: "Rappels de cours et dates d'examen.",
    stud_notif1: "Cours demain à 09:00",
    stud_notif2: "Mock théorie vendredi",
    student_results: "Résultats pratiques",
    student_results_desc: "Performance théorie et rapports téléchargeables.",
    stud_res1: "Dernier mock : 36 / 40 (90%)",
    stud_res2: "Temps de réaction moyen : 1,1s",
    stud_res3: "Télécharger les résultats (PDF)",
    test_label: "Témoignages",
    test_title: "Histoires de réussite.",
    test1_text: "« Réussi du premier coup ! Les sessions de nuit ont tout changé. »",
    test1_meta: "Examen réussi • Tunis",
    test2_text: "« Feedback clair après chaque mock. Moniteurs top. »",
    test2_meta: "Permis auto • Sousse",
    test3_text: "« Autoroute et parking impeccables. Planning facile. »",
    test3_meta: "Permis manuel • Sfax",
    blog_label: "Idées blog",
    blog_title: "Guides pour conduire serein.",
    blog1_title: "Réussir l'examen du premier coup",
    blog1_desc: "Checklist, attentes de l'examinateur et mindset.",
    blog2_title: "Astuces pour conducteurs anxieux",
    blog2_desc: "Respiration, scénarios et confiance progressive.",
    blog3_title: "Différence entre manuelle et automatique",
    blog3_desc: "Pour/contre et choix selon vos objectifs en Tunisie.",
    blog4_title: "Comment choisir un moniteur",
    blog4_desc: "Certifs à vérifier et questions à poser avant de réserver.",
    faq_label: "FAQ & politiques",
    faq_title: "Tout ce qu'il faut savoir.",
    faq_q1: "Quels véhicules utilisez-vous ?",
    faq_a1: "Véhicules double commande, manuelle et auto, entièrement assurés.",
    faq_q2: "Proposez-vous des cours multilingues ?",
    faq_a2: "Oui : arabe, français et anglais — choisissez lors de la réservation.",
    faq_q3: "Politique de remboursement",
    faq_a3: "48h d'anticipation pour annuler. Les packs non utilisés sont remboursables (frais admin).",
    faq_q4: "Conditions générales",
    faq_a4: "Comportement sécurisé, pièce d'identité valide, paiements sécurisés SSL.",
    faq_q5: "Support chat",
    faq_a5: "Discutez pour le planning, les paiements ou des conseils rapides.",
    contact_label: "Contact & localisation",
    contact_title: "Contactez-nous, passez nous voir ou discutez en direct.",
    contact_name: "Votre nom",
    contact_message: "Message",
    contact_send: "Envoyer",
    contact_hours: "Horaires",
    contact_hours_text: "Lun–Ven : 08h–19h • Sam : 09h–14h",
    whatsapp_btn: "WhatsApp",
    contact_location: "Agence Tunis centre",
    contact_phone: "+216 00 000 000",
    contact_email: "info@tunisiadrive.tn",
    footer_text: "Prêt à conduire en confiance ? Réservez votre première leçon.",
    footer_terms: "Conditions",
    footer_refund: "Remboursement",
    footer_support: "Chat & support",
    chat_toggle: "Chat en direct",
    chat_title: "Support en direct",
    chat_sub: "Répond en général en 2 minutes",
    chat_welcome: "Salut ! Besoin d'aide pour réserver ou comprendre l'examen ?",
    chat_send: "Envoyer",
    chat_reply: "Merci ! Un coach vous répond dans quelques minutes.",
    alert_booking: "Votre cours est réservé ! Un email de confirmation arrive bientôt.",
    alert_contact: "Message envoyé ! Nous vous répondons sous 1 heure ouvrée.",
    alert_login: "Connecté (démo). Consultez vos prochains cours ci-dessous.",
    ph_name: "Nom complet",
    ph_contact_email: "vous@email.com",
    ph_message: "Comment pouvons-nous aider ?",
    ph_email: "Email",
    ph_password: "Mot de passe",
    ph_chat: "Tapez votre question...",
  },
  ar: {
    brand: "أكاديمية تونسيا درايف",
    brand_sub: "مدرسة تعليم السياقة",
    nav_home: "الرئيسية",
    nav_about: "من نحن",
    nav_services: "الخدمات",
    nav_booking: "الحجوزات",
    nav_prices: "الأسعار",
    nav_learning: "الموارد",
    nav_contact: "اتصل بنا",
    nav_cta: "احجز الآن",
    hero_badge: "تونس • تدريب حديث وآمن",
    hero_title: "قد بثقة، قد بأمان.",
    hero_sub: "دروس حديثة، مدربون معتمدون، وتخطيط ذكي للنجاح السريع.",
    cta_book: "احجز الآن",
    cta_contact: "تواصل معنا",
    cta_prices: "عرض الأسعار",
    stat_success: "نسبة النجاح",
    stat_students: "عدد المتدربين",
    stat_languages: "اللغات: عربي / فرنسي / إنجليزي",
    hero_car1_title: "تدريب مريح",
    hero_car1_sub: "سيارات مزدوجة التحكم",
    hero_car2_title: "إتقان كل الطرق",
    hero_car2_sub: "مدينة • طريق سريع • ليل",
    badge_cert: "مدربون معتمدون ومرخَّصون",
    badge_schedule: "مواعيد مرنة",
    badge_payment: "دفع آمن",
    about_label: "من نحن",
    about_title: "إتقان القيادة في تونس.",
    about_text:
      "أكاديمية تونسيا درايف تمزج الخبرة المحلية بالتدريب الحديث. من أول درس إلى يوم الامتحان، نرافقك بخطط واضحة وردود فعل دقيقة.",
    about_history_title: "تاريخنا",
    about_history_text: "تأسست سنة 2010 في تونس وتخدم المتدربين في مختلف المناطق.",
    about_mission_title: "مهمتنا وقيمنا",
    about_mission_text: "السلامة والاحترافية ونِسَب نجاح واضحة في كل حصة.",
    chip_safety: "السلامة أولاً",
    chip_prof: "تدريب احترافي",
    chip_success: "نسبة نجاح عالية",
    about_team_title: "مدربون معتمدون",
    about_instr1: "10 سنوات خبرة • عادي",
    about_instr2: "طريق سريع وقيادة ليلية",
    about_instr3: "نظري وتحضير الامتحان",
    about_certs: "مرخَّص من وزارة النقل • قيادة دفاعية • إسعافات أولية",
    services_label: "البرامج",
    services_title: "خدمات لكل سائق.",
    svc_manual: "دروس عادي وأوتوماتيك",
    svc_intensive: "حصص مكثفة",
    svc_intensive_desc: "مسار سريع مع تدريب يومي لتكون جاهزاً بسرعة.",
    svc_night: "تدريب القيادة الليلية",
    svc_night_desc: "تحكم في الرؤية وآداب الأضواء وإدارة التعب.",
    svc_highway: "ممارسة الطريق السريع",
    svc_highway_desc: "الاندماج والتجاوز وضبط السرعة مع مدرب.",
    svc_parking: "تدريب الاصطفاف",
    svc_parking_desc: "موازي، عمودي، وعلى المرتفع حتى الثقة التامة.",
    svc_exam: "تحضير الامتحان",
    svc_exam_desc: "محاكاة نظري وعملي بمعايير التصحيح الرسمية.",
    svc_manual_desc: "مكيف حسب اختيارك مع سيارات مزدوجة التحكم.",
    booking_label: "الحجوزات والجدولة",
    booking_title: "احجز أونلاين، اختر المدرب، وادفع بأمان.",
    booking_text: "احجز الحصص، عادي أو أوتوماتيك، وادِر جدولك من مكان واحد.",
    form_lesson: "نوع الحصة",
    form_instructor: "اختر المدرب",
    form_date: "اختر التاريخ",
    form_time: "اختر الوقت",
    form_package: "الباقة",
    form_payment: "الدفع الآمن",
    form_submit: "تأكيد الحجز",
    opt_manual1: "عادي - ساعة",
    opt_manual2: "عادي - ساعتان",
    opt_auto1: "أوتوماتيك - ساعة",
    opt_auto2: "أوتوماتيك - ساعتان",
    opt_intensive: "مكثف (10س أسبوعياً)",
    opt_exam_pack: "باقة الامتحان",
    opt_single: "حصة مفردة",
    opt_5h: "باقة 5س",
    opt_10h: "باقة 10س",
    opt_20h: "باقة 20س",
    opt_card: "بطاقة بنكية",
    opt_transfer: "تحويل فوري",
    opt_cash: "دفع نقداً في المكتب",
    student_area_title: "منطقة الطالب",
    student_area_text: "سجّل الدخول لرؤية الجدول والتقدم والوثائق.",
    login_btn: "دخول الطالب",
    progress_label: "متابعة التقدم",
    prog_item1: "✔ وحدات النظري: 80%",
    prog_item2: "✔ قيادة المدينة: 70%",
    prog_item3: "• تمارين الاصطفاف: 50%",
    notif_label: "الدروس القادمة",
    notif_item1: "الثلاثاء 10:00 — عادي مع أمين",
    notif_item2: "الخميس 18:00 — قيادة ليلية مع ليلى",
    notif_item3: "السبت 09:00 — محاكاة امتحان مع سامي",
    docs_label: "وثائق الامتحان",
    doc_item1: "نتائج اختبار نظري (PDF)",
    doc_item2: "قائمة التحقق العملية",
    doc_item3: "نسخ التأمين والرخصة",
    prices_label: "الأسعار",
    prices_title: "أسعار واضحة وباقات مرنة.",
    price_hourly: "السعر بالساعة",
    price_hour_desc: "عادي أو أوتوماتيك • السيارة متوفرة",
    price_packages: "الباقات",
    price_package_text: "مثالي للتقدم مع توفير.",
    price_exam: "باقات الامتحان",
    price_exam1: "اختبار تجريبي + ملاحظات",
    price_exam2: "سيارة ومدرب يوم الامتحان",
    price_exam3: "مساعدة في المواعيد والأوراق",
    price_discounts: "تخفيضات",
    disc_student: "تخفيض للطلاب -10%",
    disc_group: "تخفيض للمجموعات -15%",
    disc_friend: "ركوبة مجانية لصديق تحضره معك",
    learning_label: "الموارد التعليمية",
    learning_title: "نظري وتطبيقي ونصائح في مكان واحد.",
    learn_theory: "مواد الامتحان النظري",
    learn_signs: "شرح إشارات المرور",
    learn_rules: "قواعد الطريق في تونس",
    learn_pdfs: "ملفات PDF للتحميل",
    learn_tips: "نصائح القيادة",
    tip_parallel: "كيف تصف موازياً",
    tip_roundabout: "إدارة الدورانات",
    tip_hill: "بداية المرتفع",
    tip_mistakes: "أخطاء المبتدئين لتجنبها",
    learn_quiz: "اختبارات تدريبية",
    learn_quiz_desc: "أسئلة متعددة باختيار مع تعليقات فورية ومحاكاة مؤقتة.",
    learn_quiz_btn: "ابدأ اختباراً تجريبياً",
    quiz1: "اختبار 1 — قواعد الطريق",
    quiz2: "اختبار 2 — الإشارات والعلامات",
    quiz3: "اختبار تجريبي — 40 سؤالاً",
    learn_videos: "فيديوهات تعليمية",
    learn_advice: "نصائح المرشدين وشرح بصري للحركات.",
    student_label: "منطقة الطالب",
    student_title: "تابع التقدم والإشعارات والنتائج.",
    student_progress: "متابعة التقدم",
    student_progress_desc: "شاهد إنجازاتك حسب الفئة.",
    stud_prog1: "الدوارات: 80%",
    stud_prog2: "الاصطفاف: 70%",
    stud_prog3: "الطريق السريع: 65%",
    student_notifications: "إشعارات",
    student_notifications_desc: "تذكيرات بالدروس ومواعيد الامتحان.",
    stud_notif1: "درس غداً الساعة 09:00",
    stud_notif2: "اختبار نظري تجريبي الجمعة",
    student_results: "نتائج الممارسة",
    student_results_desc: "أداء الاختبار النظري وتقارير قابلة للتنزيل.",
    stud_res1: "آخر اختبار: 36 / 40 (90%)",
    stud_res2: "متوسط زمن الاستجابة: 1.1 ثانية",
    stud_res3: "تحميل النتائج (PDF)",
    test_label: "آراء المتدربين",
    test_title: "قصص نجاح طلابنا.",
    test1_text: "“نجحت من أول مرة! الحصص الليلية فرقت كثيراً.”",
    test1_meta: "نجاح الامتحان • تونس",
    test2_text: "“أحببت التعليقات بعد كل اختبار تجريبي. مدربون رائعون.”",
    test2_meta: "رخصة أوتوماتيك • سوسة",
    test3_text: "“تدريب الطريق السريع والاصطفاف كان ممتاز. الحجز سهل.”",
    test3_meta: "رخصة عادي • صفاقس",
    blog_label: "أفكار المدونة",
    blog_title: "إرشادات لسياقة واثقة.",
    blog1_title: "كيف تنجح في الامتحان من أول مرة",
    blog1_desc: "قائمة استعداد، توقعات الممتحن، ونصائح نفسية.",
    blog2_title: "نصائح للسائقين المتوترين",
    blog2_desc: "تنفس، تمارين مواقف، وبناء الثقة تدريجياً.",
    blog3_title: "الفرق بين العادي والأوتوماتيك",
    blog3_desc: "إيجابيات وسلبيات وكيف تختار حسب هدفك في تونس.",
    blog4_title: "كيف تختار مدرب سياقة",
    blog4_desc: "شهادات يجب التحقق منها وأسئلة قبل الحجز.",
    faq_label: "الأسئلة والسياسات",
    faq_title: "كل ما تحتاج معرفته.",
    faq_q1: "ما السيارات المستخدمة؟",
    faq_a1: "سيارات مزدوجة التحكم، عادي وأوتوماتيك، مؤمّنة بالكامل.",
    faq_q2: "هل الدروس بعدة لغات؟",
    faq_a2: "نعم: عربي، فرنسي، إنجليزي — اختر عند الحجز.",
    faq_q3: "سياسة الاسترجاع",
    faq_a3: "إشعار 48 ساعة للإلغاء. الباقات غير المستعملة مسترجعة مع رسوم بسيطة.",
    faq_q4: "الشروط والأحكام",
    faq_a4: "سلوك آمن وهوية سارية، والدفع مؤمّن بـ SSL.",
    faq_q5: "دعم الدردشة",
    faq_a5: "تحدث معنا للجدولة أو الدفع أو النصائح السريعة.",
    contact_label: "الاتصال والموقع",
    contact_title: "تواصل معنا أو زرنا أو دردش فوراً.",
    contact_name: "اسمك",
    contact_message: "رسالتك",
    contact_send: "إرسال",
    contact_hours: "ساعات العمل",
    contact_hours_text: "الاثنين–الجمعة: 08:00–19:00 • السبت: 09:00–14:00",
    whatsapp_btn: "واتساب",
    contact_location: "مركز تونس",
    contact_phone: "+216 00 000 000",
    contact_email: "info@tunisiadrive.tn",
    footer_text: "جاهز للقيادة بثقة؟ احجز حصتك الأولى اليوم.",
    footer_terms: "الشروط والأحكام",
    footer_refund: "سياسة الاسترجاع",
    footer_support: "دردشة ودعم",
    chat_toggle: "دردشة مباشرة",
    chat_title: "دعم مباشر",
    chat_sub: "عادة نرد خلال دقيقتين",
    chat_welcome: "مرحباً! تحتاج مساعدة في الحجز أو فهم الامتحان؟",
    chat_send: "إرسال",
    chat_reply: "شكراً! سيجيبك المدرب خلال دقائق.",
    alert_booking: "تم حجز حصتك! سنرسل تأكيداً على البريد قريباً.",
    alert_contact: "تم إرسال الرسالة! سنتواصل معك خلال ساعة عمل.",
    alert_login: "تم تسجيل الدخول (تجريبي). راجع الدروس القادمة أدناه.",
    ph_name: "الاسم الكامل",
    ph_contact_email: "you@email.com",
    ph_message: "كيف يمكننا المساعدة؟",
    ph_email: "البريد الإلكتروني",
    ph_password: "كلمة المرور",
    ph_chat: "اكتب سؤالك...",
  },
};

let currentLang = "en";

function getText(key) {
  const set = translations[currentLang] || translations.en;
  return set[key] || translations.en[key] || "";
}

function applyLanguage(lang) {
  const set = translations[lang] || translations.en;
  currentLang = lang;
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  document.querySelectorAll("[data-lang-key]").forEach((el) => {
    const key = el.getAttribute("data-lang-key");
    if (set[key]) el.textContent = set[key];
  });
  document.querySelectorAll("[data-placeholder-key]").forEach((el) => {
    const key = el.getAttribute("data-placeholder-key");
    if (set[key]) el.setAttribute("placeholder", set[key]);
  });
}

function smoothAnchors() {
  document.querySelectorAll('a[href^="#"]').forEach((anchor) => {
    anchor.addEventListener("click", (e) => {
      const href = anchor.getAttribute("href");
      if (!href || href === "#") return;
      const target = document.querySelector(href);
      if (target) {
        e.preventDefault();
        target.scrollIntoView({ behavior: "smooth", block: "start" });
      }
    });
  });
}

function initBooking() {
  const bookingForm = document.getElementById("booking-form");
  bookingForm?.addEventListener("submit", (e) => {
    e.preventDefault();
    alert(getText("alert_booking"));
    bookingForm.reset();
  });
}

function initContact() {
  const contactForm = document.getElementById("contact-form");
  contactForm?.addEventListener("submit", (e) => {
    e.preventDefault();
    alert(getText("alert_contact"));
    contactForm.reset();
  });
}

function initLogin() {
  const loginForm = document.getElementById("login-form");
  const notifications = document.getElementById("notifications-list");
  loginForm?.addEventListener("submit", (e) => {
    e.preventDefault();
    if (notifications) {
      notifications.innerHTML = `
        <li>${getText("notif_item1")}</li>
        <li>${getText("notif_item2")}</li>
        <li>${getText("notif_item3")}</li>
      `;
    }
    alert(getText("alert_login"));
  });
}

function initChat() {
  const widget = document.getElementById("chat-widget");
  const openBtn = document.getElementById("chat-toggle");
  const closeBtn = document.getElementById("chat-close");
  const chatForm = document.getElementById("chat-form");
  const chatBody = document.getElementById("chat-body");
  const chatText = document.getElementById("chat-text");

  const toggle = (show) => {
    if (show) {
      widget.style.display = "flex";
      chatText?.focus();
    } else {
      widget.style.display = "none";
    }
  };

  openBtn?.addEventListener("click", () => toggle(true));
  closeBtn?.addEventListener("click", () => toggle(false));

  chatForm?.addEventListener("submit", (e) => {
    e.preventDefault();
    const value = chatText?.value.trim();
    if (!value) return;
    chatBody?.insertAdjacentHTML("beforeend", `<div class="chat-message user">${value}</div>`);
    chatText.value = "";
    setTimeout(() => {
      chatBody?.insertAdjacentHTML(
        "beforeend",
        `<div class="chat-message bot">${getText("chat_reply")}</div>`
      );
      chatBody?.scrollTo({ top: chatBody.scrollHeight, behavior: "smooth" });
    }, 600);
    chatBody?.scrollTo({ top: chatBody.scrollHeight, behavior: "smooth" });
  });
}

function initLanguage() {
  const select = document.getElementById("language-select");
  const defaultLang = "en";
  if (select) select.value = defaultLang;
  applyLanguage(defaultLang);
  select?.addEventListener("change", (e) => {
    const lang = e.target.value;
    applyLanguage(lang);
  });
}

document.addEventListener("DOMContentLoaded", () => {
  smoothAnchors();
  initBooking();
  initContact();
  initLogin();
  initChat();
  initLanguage();
});

